# Copyright 2019 VMware, all rights reserved.
# This software is released under MIT license.
# The full license information can be found in LICENSE in the root directory of this project.


language: node_js

node_js:
  - "8.15.1"
services:
  - docker

before_install:
- docker-compose up

script:
- npm run lint
- docker-compose up run supply-chain npm run lint
